-- Create the registrations table if it doesn't exist
create table if not exists public.registrations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  service_key text not null,
  full_name text not null,
  email text not null,
  phone text not null,
  address text,
  occupation text,
  next_of_kin_name text,
  next_of_kin_phone text,
  notes text,
  status text default 'new'::text,
  source text default 'website'::text
);

-- Set up Row Level Security (RLS)
-- Enable RLS
alter table public.registrations enable row level security;

-- Create a policy that allows the service role (backend) to insert data
-- We use 'do nothing' on conflict for policy creation to avoid errors if run multiple times
do $$
begin
  if not exists (
    select from pg_catalog.pg_policies 
    where tablename = 'registrations' 
    and policyname = 'Enable access to service_role'
  ) then
    create policy "Enable access to service_role"
    on public.registrations
    as permissive
    for all
    to service_role
    using (true)
    with check (true);
  end if;
end
$$;
